server:
  port: 9001

spring:
  application:
    name: AUTHENTICATOR
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: 0fef9003c9fde2
    password: ca86576b238fe5
    properties:
      mail:
        smtp:
          auth: PLAIN
          starttls:
            enable: true
    protocol: smtp
    tls: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  expiration:
    time: 900000

management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-methods: OPTIONS, GET, POST
        allowed-headers: "*"
        allowed-origins: "*"
      exposure:
        include: "*"
