server:
  port: 9003

spring:
  application:
    name: RENTAL-SEARCH

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  expiration:
    time: 900000

management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-methods: OPTIONS, GET, POST
        allowed-headers: "*"
        allowed-origins: "*"
      exposure:
        include: "*"